# Generated by Django 5.1.1 on 2025-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addres',
            field=models.TextField(null=True),
        ),
    ]
