# Generated by Django 5.1.1 on 2025-04-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
